version: "3"

services:

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${ENV_DB_USERNAME}
      - POSTGRES_DB=${ENV_DB_NAME}

  scheduler:
    image: zdrovi/scheduler:latest
    container_name: scheduler
    ports:
      - "8080:8080"
    environment:
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - ./scheduler:/app
    command:
      - java -jar service.jar --spring.config.location=file:./application.yaml