version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - sudo apt-get update && sudo apt-get install -y gnupg software-properties-common
      - wget -O- https://apt.releases.hashicorp.com/gpg | gpg --dearmor | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
      - echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | \
      - sudo apt update
      - sudo apt-get install terraform
  pre_build:
    commands:
      - terraform init
      - terraform validate

  build:
    commands:
      - terraform plan
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Terraform apply completed on `date`"

artifacts:
  files:
    - '**/*'