version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.10
    commands:
      - sudo yum install -y yum-utils
      - sudo yum-config-manager --add-repo https://rpm.releases.hashicorp.com/AmazonLinux/hashicorp.repo
      - sudo yum -y install terraform
      - cd infrastructure/cloud/infra
  pre_build:
    commands:
      - terraform init
      - terraform validate

  build:
    commands:
      - terraform plan
      - terraform apply -auto-approve

  post_build:
    commands:
      - echo "Terraform apply completed on `date`"

artifacts:
  files:
    - '**/*'